spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://47.97.112.149:3306/gulimall_sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-coupon
#服务注册名 application name
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
#主键自增
server:
  port: 7000

#server-addr  nacos服务注册中心